/**:
  ros__parameters:
    apriltags:
      robot_table_tag_size: 0.173 # m
      work_area_tag_size: 0.055 # m
    robot_table:
      width: 0.605 # m
      length: 0.911 # m
      height: 0.827 # m
      y_tag_edge_to_base: 0.3 # m
      x_tag_edge_to_table_edge: 0.023 # m
    ceiling_height: 2.4 # m
    side_wall:
      distance: 1.0 # m
      height: 2.4 # m
    back_wall:
      distance: 0.75 # m
      height: 0.46 # m
    lightsaber:
      diameter: 0.033 # m
      full_length: 1.122 # m
      grip_offset: 0.15 # m
      start_location:
        x: 0.5715 # m
        y: -0.263525 # m
        z: -0.18 # m
      lift_height: 0.5 # m
    gripper:
      height: 0.08 # m, height of Franka attached gripper to avoid collisions
      tcp_offset: 0.036 # m, offset from panda_hand_tcp_frame
    depth_filter:
      min_offset: 0.075 # m
      max_offset: 0.5 # m