string link_name # link to attach to 
geometry_msgs/Point position # position to place obstacle to
float64 length  # length of the obstacle
float64 width   # width of the obstacle   
float64 height  # height of the obstacle 
string id       # id of the obstacle
uint8 type  # type of object's shape
bool delete_obstacle     # delete flag to remove obstacle
---